# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [7]:
from typing import List
import re

def tokenize_words(text: str) -> List[str]:
    """Tokenize text into words using regex."""
    return re.findall(r"[A-Za-z]+(?:'[A-Za-z]+)?|\d+(?:\.\d+)?", text)

def tokenize_sentence(text: str) -> List[str]:
    """Tokenize text into sentences using regex."""
    normalized = re.sub(r"\s+", " ", text.strip())

    # replacements so for example p.m. wont be detected as end of sentence.
    replacements = {"p.m.": "p_m_abbr", "a.m.": "a_m_abbr", "e.g.": "e_g_abbr", "i.e.": "i_e_abbr"}
    for original, placeholder in replacements.items():
        normalized = normalized.replace(original, placeholder)

    parts = re.split(r"(?<=[.!?])(?:\s+|(?=[A-Z]))", normalized)

    sentences = []
    # revert placeholder back to original
    for part in parts:
        part = part.strip()
        if not part:
            continue
        for original, placeholder in replacements.items():
            part = part.replace(placeholder, original)
        sentences.append(part)

    return sentences

text = "Here we go again. I was supposed to add this text later.\
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try.\
And one last sentence, just so you can test you tokenizers better."

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))


Tokenized sentences:
['Here we go again.', 'I was supposed to add this text later.', "Well, it's 10.p.m. here, and I'm actually having fun making this course.", ':oI hope you are getting along fine with this presentation, I really did try.', 'And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later', 'Well', "it's", '10', 'p', 'm', 'here', 'and', "I'm", 'actually', 'having', 'fun', 'making', 'this', 'course', 'oI', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation', 'I', 'really', 'did', 'try', 'And', 'one', 'last', 'sentence', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [11]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

file = open("../datasets/trump.txt", "r",encoding="utf-8") 
trump = file.read()
words = word_tokenize(trump)

# fill the gap and imports


tags = nltk.pos_tag(words)

print(tags[:100])

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/michalharasim/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/michalharasim/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


[('Thank', 'NNP'), ('you', 'PRP'), ('very', 'RB'), ('much', 'RB'), ('.', '.'), ('Mr.', 'NNP'), ('Speaker', 'NNP'), (',', ','), ('Mr.', 'NNP'), ('Vice', 'NNP'), ('President', 'NNP'), (',', ','), ('Members', 'NNP'), ('of', 'IN'), ('Congress', 'NNP'), (',', ','), ('the', 'DT'), ('First', 'NNP'), ('Lady', 'NNP'), ('of', 'IN'), ('the', 'DT'), ('United', 'NNP'), ('States', 'NNPS'), (',', ','), ('and', 'CC'), ('citizens', 'NNS'), ('of', 'IN'), ('America', 'NNP'), (':', ':'), ('Tonight', 'NN'), (',', ','), ('as', 'IN'), ('we', 'PRP'), ('mark', 'VBP'), ('the', 'DT'), ('conclusion', 'NN'), ('of', 'IN'), ('our', 'PRP$'), ('celebration', 'NN'), ('of', 'IN'), ('Black', 'NNP'), ('History', 'NNP'), ('Month', 'NNP'), (',', ','), ('we', 'PRP'), ('are', 'VBP'), ('reminded', 'VBN'), ('of', 'IN'), ('our', 'PRP$'), ('Nation', 'NN'), ("'s", 'POS'), ('path', 'NN'), ('towards', 'NNS'), ('civil', 'JJ'), ('rights', 'NNS'), ('and', 'CC'), ('the', 'DT'), ('work', 'NN'), ('that', 'WDT'), ('still', 'RB'), ('remains

## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [18]:
import spacy
from spacy.cli import download

with open("../datasets/trump.txt", "r", encoding="utf-8") as file:
    trump = file.read()

model_name = "en_core_web_sm"
try:
    nlp = spacy.load(model_name)
except OSError:
    download(model_name)
    nlp = spacy.load(model_name)

doc = nlp(trump)

sentences = list(doc.sents)[-10:]
nouns_by_sentence = []

for sent in sentences:
    nouns = [token.text for token in sent if token.pos_ in {"NOUN", "PROPN"}]
    nouns_by_sentence.append({
        "sentence": sent.text.strip(),
        "nouns": nouns
    })

for idx, item in enumerate(nouns_by_sentence, 1):
    print(f"{idx}. {item['sentence']}")
    print(f"   nouns: {item['nouns']}")


1. When we fulfill this vision, when we celebrate our 250 years of glorious freedom, we will look back on tonight as when this new chapter of American greatness began.
   nouns: ['vision', 'years', 'freedom', 'tonight', 'chapter', 'greatness']
2. The time for small thinking is over.
   nouns: ['time', 'thinking']
3. The time for trivial fights is behind us.
   nouns: ['time', 'fights']
4. We just need the courage to share the dreams that fill our hearts, the bravery to express the hopes that stir our souls, and the confidence to turn those hopes and those dreams into action.
   nouns: ['courage', 'dreams', 'hearts', 'bravery', 'hopes', 'souls', 'confidence', 'hopes', 'dreams', 'action']
5. From now on, America will be empowered by our aspirations, not burdened by our fears; inspired by the future, not bound by failures of the past; and guided by our vision, not blinded by our doubts.
   nouns: ['America', 'aspirations', 'fears', 'future', 'failures', 'past', 'vision', 'doubts']
6. I am

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [20]:
import numpy as np

class BagOfWords:
    """Basic BoW implementation."""

    def __init__(self):
        self.__bow_list = []

    def __tokenize(self, text: str) -> list:
        tokens = tokenize_words(text)
        return [token.lower() for token in tokens]

    def fit_transform(self, corpus: list):
        docs_tokens = [self.__tokenize(text) for text in corpus]

        vocab = sorted({token for tokens in docs_tokens for token in tokens})
        self.__bow_list = vocab
        token_to_col = {token: idx for idx, token in enumerate(vocab)}

        bow = np.zeros((len(corpus), len(vocab)), dtype=int)
        for row, tokens in enumerate(docs_tokens):
            for token in tokens:
                bow[row, token_to_col[token]] += 1

        return bow

    def get_feature_names(self) -> list:
        return self.__bow_list

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]

vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

print(vectorizer.get_feature_names())
len(vectorizer.get_feature_names())


[[0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 2 1 0 0 1 0 1 0 0]]
['a', 'as', 'bag', 'based', 'below', 'can', 'counting', 'document', 'documents', 'gives', 'is', 'matrix', 'most', 'multiple', 'occur', 'occurences', 'of', 'on', 'once', 'only', 'pretty', 'really', 'see', 'sparse', 'the', 'third', 'this', 'throughout', 'us', 'words', 'you']


31

## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [29]:
from nltk.book import *
import random
wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

In [31]:
def clean_generated(text: str) -> str:
    # Remove whitespace before end punctuation
    text = re.sub(r"\s+([.!?])", r"\1", text)

    # Capitalize first char
    text = text.strip()
    if text:
        text = text[0].upper() + text[1:]

    # Capitalize first letter
    text = re.sub(r"(?<=[.!?]\s)([a-z])", lambda m: m.group(1).upper(), text)
    return text

N=5

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq = None

counts = ngram_freqs(ngrams)

if start_seq is None:
    start_seq = random.choice(list(counts.keys()))
else:
    start_seq = start_seq.lower().strip()
    if len(start_seq.split()) != N - 1 or start_seq not in counts:
        start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower()

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.', '!', '?')) else 0

generated = clean_generated(generated)
print(generated)


Was only 15 of the size of the hitter ties are permitted even welcomed since they honorably sidestep the shame of defeat players must abide by strict rules of conduct even in their personal lives players for the Tokyo Giants for example must always wear ties when on the road. You Gotta Have Wa is the often amusing chronicle of how American ballplayers rationed to two per team fare in Japan. Despite the enormous sums of money 0 they paid to stand up at a Japanese plate a good number decide 0 it not worth it and run for home. Funny Business Soho 228 pages 17.95 by Gary Katzenstein is anything but. It the petulant complaint of an impudent American whom Sony hosted for a year while he was on a Luce Fellowship in Tokyo to the regret of both parties.
